// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_nsxl_ljvI-BOoF6xbTS8IbSHMDiC9qA',
    appId: '1:231470397469:web:0df95d32c39165f09b6ef4',
    messagingSenderId: '231470397469',
    projectId: 'saha-yatri-fef25',
    authDomain: 'saha-yatri-fef25.firebaseapp.com',
    databaseURL: 'https://saha-yatri-fef25-default-rtdb.firebaseio.com',
    storageBucket: 'saha-yatri-fef25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR-06fB2gAIXUCqqzrBEqM5Tbt7wXQg3w',
    appId: '1:231470397469:android:23fc0242a527ee8c9b6ef4',
    messagingSenderId: '231470397469',
    projectId: 'saha-yatri-fef25',
    databaseURL: 'https://saha-yatri-fef25-default-rtdb.firebaseio.com',
    storageBucket: 'saha-yatri-fef25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIjzo_VC2rCqgJu_DR48Gola2vsveKmrk',
    appId: '1:231470397469:ios:4d024f771ace5edd9b6ef4',
    messagingSenderId: '231470397469',
    projectId: 'saha-yatri-fef25',
    databaseURL: 'https://saha-yatri-fef25-default-rtdb.firebaseio.com',
    storageBucket: 'saha-yatri-fef25.appspot.com',
    iosClientId:
        '231470397469-sel1rhl01vcaa66nbf34drttrlensfad.apps.googleusercontent.com',
    iosBundleId: 'com.example.yatriApp',
  );
}
